### ISSUE TITLE
Reactify

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#1]
Upon clean install i get: 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'reactify' 

**My** project apparently needs reactify instead of the id-builder using it's own reactify

I don't know if it works this way but maybe you can solve it by requiring reactify at the start of  browserify.js and then pass the variable containing reactify into the b.transform instead of b.transform("reactify").

Kind off like this:
reactify = require("reactify")
b.transform(reactify)

**Comment by Industrial** [comment]
Hi.

I'm currently working on id-builder, so expect a new release soon. It will remove unneeded dependencies so the deps will install and run with io.js, swap out 6to5 for Babel (which has renamed) and after that I'm going to check out JSX support.

JSX Support currently works with Browserify I think, but if I'm going to use ES6 with Babel, I'm going to use Babel instead to compile the JSX, since it's already compiling the source files anyway. Leaves everything cleaner for Browserify.

**Comment by Industrial** [comment]
How are you experiencing id-builder @hawkerboy7 ? Is it faster/nicer then id-project ?

**Comment by hawkerboy7** [comment]
It's a lot faster indeed @Industrial11 I do have some problems getting every functionality working though

**Comment by Industrial** [comment]
id-builder now demands (when the option is turned on) all .js files to be ES6 and compiled with Babel.js so that should cover JSX. It's baked in. This also happens before the Browserify step meaning Browserify never has to worry about this, so that should be a speedup in watchify recompile times I hope.
