### ISSUE TITLE
Integrate with AmokJS

### ISSUE THREAD

**Issue by Industrial** [Industrial/id-builder#34]
AmokJS is a tool that uses the chrome debugger to inject JavaScript state into the browser, allowing you to code without having to refresh. I think it might work nicely with BrowserSync or replace some of it's functionality.

**Comment by Industrial** [comment]
From Gitterm.im:

"Just point amok to the url as the entrypoint, sounds like it would fit your use case
e.g
amok http://localhost:9090 --client chrome
So amok wont replace browsersync, as they do radically different things and have no overlap
Browsersync can be run as a proxy as far as i am aware tho
Oh launch it from the working directory, I should probably add an option for specifying that."

**Comment by hawkerboy7** [comment]
Sound nice n fancy but it is that necessary using a app.bundle.js?
The time profit you get,if I understand correctly, is that you app.bundle.js will be injected instead of refreshing the browser. So you'll get 0.2, maybe max 1 second, depending on the time difference of you browser reloading or injecting?
Might not be worth the coding in this case?

**Comment by Industrial** [comment]
Imagine having a setTimeout() running that prints something to the DOM every millisecond

If you use AmokJS you can make edits to your code and it will change in the browser without having to reload.

**Comment by hawkerboy7** [comment]
Yes but then you insert a new app.bundle.js right? And since most (if not all) of your html in inside you app.bundle.js your app basically is starting over again right?
